// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlPZ8pYDUXzkz5hngjjsAAvqYw5qcAGOc',
    appId: '1:148215676302:web:b24bee48d69c3dce93f8df',
    messagingSenderId: '148215676302',
    projectId: 'admin-project-70a9e',
    authDomain: 'admin-project-70a9e.firebaseapp.com',
    storageBucket: 'admin-project-70a9e.appspot.com',
    measurementId: 'G-ZGWNPYK6S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc9B9TUFVNZNW9-is7y-qFpijh552kTsA',
    appId: '1:148215676302:android:9d25be0bf7d5442593f8df',
    messagingSenderId: '148215676302',
    projectId: 'admin-project-70a9e',
    storageBucket: 'admin-project-70a9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkuW1SKaRVvlzdAIPW96DOkTGLFr2BBYk',
    appId: '1:148215676302:ios:24137ff293fe6a6a93f8df',
    messagingSenderId: '148215676302',
    projectId: 'admin-project-70a9e',
    storageBucket: 'admin-project-70a9e.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkuW1SKaRVvlzdAIPW96DOkTGLFr2BBYk',
    appId: '1:148215676302:ios:a171d7cad2d12a8293f8df',
    messagingSenderId: '148215676302',
    projectId: 'admin-project-70a9e',
    storageBucket: 'admin-project-70a9e.appspot.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
